### PR TITLE
[Docker] Evolution of Docker environment useful to run stand-alone production instance

### PR DESCRIPTION
**Pull request by francescobianco**
Hi! Myddleware!

This is the evolution of Docker environment useful to run a stand-alone Docker production instance in a linux machine
It require only this tools to run

- GNU Make (to process Makefile)
- Docker (at least version 20)
- Docker Compose (at leat version 1.27)

At the moment there is not good solution to connect with Microsoft Database, 
I require a bit of time to test the following library DBLIB adn PHP_SQLSRV on PHP 7.4

From my point of view, this is a good Docker Environment to run a working copy of Myddleware

Please Test it from your side, I'm ready to fix or any other missing

Read the follow file to have instruction for running Docker
- https://github.com/opencrmitalia-official/myddleware/blob/I2452/docker/README.md

### CODE REVIEW

**Comment by stlgaits** [comment]
Hello @francescobianco I am testing this but during 'make setup' I keep bumping into the same error and so the execution fails, not sure why but the mysql5.7.28 cntainer keeps restarting after make install : 
image
image

Any idea what I can do ?

I am testing this on an Ubuntu 20.04 WSL mount with Docker Desktop 4.4.3

**Comment by stlgaits** [comment]
This is the error log from the MySQL container
image

**Comment by francescobianco** [comment]
Hi @EstelleMyddleware @Myddleware a new FIX is the pull request just for the WAIT command in Makefile
https://github.com/Myddleware/myddleware/pull/644/commits/2ea320cca3a34cc537ff8d0065cd2ce0bbf1186b

Try to merge it

Attention before repeat the `make setup` call a `make down`

**Comment by stlgaits** [comment]
Thanks, will test it straight away and let you know.

**Comment by stlgaits** [comment]
Got it up and running with the update and it's working like a charm ! Thanks a lot for your reactivity !!!!
image
Just a couple of questions out of curiosity : 
- what is the point of separating these 2 from the rest of the composer  : 
```
require-vtiger-client:
	@docker-compose -f docker-compose.yml run --rm myddleware php composer2.phar require javanile/vtiger-client:0.0.28 -vvvv --ignore-platform-reqs --no-scripts

require-woocommerce-client:
	@docker-compose -f docker-compose.yml run --rm myddleware php composer.phar require automattic/woocommerce:^3.0.0 -vvvv --ignore-platform-reqs --no-scripts
```
- and also do we absolutely need MSSQL container ?

We will carry out functional tests on this version to make sure connectors & rules are working properly, but once again thank you so much for all your hard work.

**Comment by stlgaits** [comment]
Hello @francescobianco, I've added /var/logs/* to main .gitignore but I was wondering whether we should add this folder too : 
image
/docker/etc/openvpn ?
because otherwise git wants me to commit them
image
Also, other question, is it safe to disable Oracle ? I'm asking because we have some users who may not need it so I would like to provide them with a lighter image if possible
Let me know what you think.
TIA

**Comment by stlgaits** [comment]
Hi @francescobianco actually I've tested this again locally and I keep getting this error message in the MySQL logs when I run make setup : 
image
image
I've tried doing make down first, as well as emptying the contents of /docker/var/mysql/ folder too before running make setup but it still generates the same error and so the execution doesn't finish. 
image
Any idea about how come this happens on my localhost (not on remote server) and what I can do ?

**Comment by stlgaits** [comment]
Hi @francescobianco another question; shouldn't vtigercrm.log be in gitignore ? 
image

**Comment by francescobianco** [comment]
Yes it can be ignore it is just log

**Pull request merged**
